[package]
name = "web-rust"
version = "0.1.0"
authors = ["Matsuzaki Rei <matsuzaki.rei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
